[package]
name = "regular_polygon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.8.0"

[[bin]]
name = "regular_polygon"
path = "main.rs"
